// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SwiftST",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "SwiftST",
            targets: ["AppModule"],
            bundleIdentifier: "PaesLemeST",
            teamIdentifier: "J8D7WJR5PY",
            displayVersion: "1.0",
            bundleVersion: "1",
            additionalInfoPlistContentFilePath: "ExportCompliance.plist",
            appIcon: .placeholder(icon: .barChart),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("game_data.json")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
