// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Gamegram",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Gamegram",
            targets: ["AppModule"],
            bundleIdentifier: "com.gamegram.app",
            teamIdentifier: "J8D7WJR5PY",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gameController),
            accentColor: .presetColor(.purple),
            infoPlist: .extendingDefault(with: [
                "NSAppTransportSecurity": .dictionary([
                    "NSAllowsArbitraryLoads": .boolean(true)
                ])
            ]),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
